### PR TITLE
Allow bids of 0 value and fix interpretation of bids with 0 value

### LINKED ISSUE #163: Issues with bids of 0 value
h/t @falci

Bob doesn't normally allow bids of `0` value, but this can be sidestepped by entering a value of `0.00000000001`:

https://github.com/kyokan/bob-wallet/blob/4c424a19580ababf08ac7b5bd22b92aebdd4c844/app/pages/Auction/BidActionPanel/BidNow.js#L189

This is one thing that should be fixed -- 6 decimal place max, as enforced here:

https://github.com/kyokan/bob-wallet/blob/65ae2106cf82624b240a2efd89cd269c85567074/app/pages/Auction/RepairBid.js#L58

The user can also use RPC calls to send a bid of `0`, which is totally valid **as long as the lockup is above the dust limit**

Unfortunately the `0` value is incorrectly interpreted as false in two places which both trigger repair bid, and prevent repair bid:

Incorrectly flagging a bid of `0` as missing (in need of repair -- this should just check for `undefined`):

https://github.com/kyokan/bob-wallet/blob/4c424a19580ababf08ac7b5bd22b92aebdd4c844/app/pages/Auction/BidActionPanel/BidNow.js#L411

Preventing value of `0` being entered as a repaired bid (this should just be a type check):

https://github.com/kyokan/bob-wallet/blob/65ae2106cf82624b240a2efd89cd269c85567074/app/pages/Auction/RepairBid.js#L62

### PR DESCRIPTION
**Pull request by pinheadmz**
Builds on top of #165 and together closes #163.

Requires https://github.com/handshake-org/hsd/pull/477 and SHOULD require https://github.com/handshake-org/hsd/pull/479

This improves the input checking for bid and disguise values. 

Users have tried sending bids with values like `0.00000000000001`, not getting an error, and then not realizing their bid value was actually `0` in this case. Users could also send `0` bids using CLI commands. These 0-value bids were misinterpreted by Bob as being falsey, leading to unexpected UI behavior.

This PR requires that bid and disguise values match a regex (6 decimal places max) and max value check.

It allows Bob users to send bids of `0` value but ONLY if there is a non-zero LOCKUP value. This is a bit of an easter-egg and I'm ok with that. (The "place bid" button won't enable unless a disguise is added). We can also try to anticipate the user's strategy and add a warning or other type of message...?

It is CRITICAL that https://github.com/handshake-org/hsd/pull/479 is included in Bob, otherwise users sending extremely low value lockups will experience their bids not relaying between peers and very likely never confirmed.

### CODE REVIEW

File: app/pages/Auction/BidActionPanel/BidNow.js [hunk 1]
```diff
@@ -105,6 +106,15 @@ class BidNow extends Component {
     }
   }
 
+  processValue = (val, field) => {
+    const value = val.match(/[0-9]*\.?[0-9]{0,6}/g)[0];
+    if (value * consensus.COIN > consensus.MAX_MONEY)
+      return;
+    if (Number.isNaN(parseFloat(value)))
```
Comment (mslipper) [inline app/pages/Auction/BidActionPanel/BidNow.js:113]: Wouldn't you want the parseFloat/isNaN check to happen before performing multiplication?

File: app/pages/Auction/BidActionPanel/BidNow.js [hunk 2]
```diff
@@ -408,7 +418,7 @@ function getTotalBids(domain) {
   for (const {bid} of domain.bids) {
     if (bid.own) {
       // This is our bid, but we don't know its value
-      if (!bid.value)
+      if (bid.value == null)
```
Comment (mslipper) [inline app/pages/Auction/BidActionPanel/BidNow.js:421]: `===`?

File: app/pages/Auction/BidHistory.js [hunk 3]
```diff
@@ -61,12 +61,12 @@ export default class BidHistory extends Component {
...
               const {month, day, year} = bid.date;
               let bidValue = 'Hidden Until Reveal';
-              if (!bid.bid && bid.own) {
+              if (bid.bid == null && bid.own) {
                 bidValue = <RepairBid
                   bid={bid}
                 />;
               }
-              if (bid.bid)
+              if (bid.bid != null)
```
Comment (mslipper) [inline app/pages/Auction/BidHistory.js:69]: `===`?

File: app/pages/Auction/BidActionPanel/BidNow.js (hunk 2 above)
Comment (pinheadmz) [reply app/pages/Auction/BidActionPanel/BidNow.js:421]: The reason is to catch both `undefined` and `null`:

```
> a = {a:1}
{ a: 1 }
> a.b
undefined
> a.b === null
false
> a.b == null
true
```

I picked up this coding style from the API modules in bcoin/hsd.

File: app/pages/Auction/BidActionPanel/BidNow.js (hunk 1 above)
Comment (pinheadmz) [reply app/pages/Auction/BidActionPanel/BidNow.js:111]: You're right, fixing. Although it turns out `NaN * Number = NaN` and `NaN > Number` is `false` so the first check would pass but the second would fail and return...

**Comment by pinheadmz** [comment]
rebase to: aa0ecbbc0d8a7c71ee81bdc85f44a07d649bbb73 

address https://github.com/kyokan/bob-wallet/pull/170#discussion_r460643305

**Comment by pinheadmz** [comment]
https://github.com/handshake-org/hsd/pull/479 is merged into hsd master, so this PR is unblocked as long as Bob pulls the latest hsd
