### PR TITLE
Bulk fixes

### LINKED ISSUE #174: [Feature / UX] Display "spendable balance" on the top bar in all UI views
Currently this info is visible in the gear menu but when actively managing bids across concurrent auctions, I want to refer to it pretty continuously. It'd save me a lot of mousing and clicking to just always show it in the top bar. Total balance is much less actionable so I don't really care about seeing it taking up the extra space, but the spendable balance is almost always relevant for me to be aware of.

### LINKED ISSUE #293: Make tree update text context aware
Do you think this should be with context of the name's last update? Like "The records you just updated will be committed in X blocks" or "The changes you've made are live now".
Not sure how to get the last UPDATE tx of a name, so now it's always shown like in the pic.

_Originally posted by @rithvikvibhu in https://github.com/kyokan/bob-wallet/issues/289#issuecomment-760686417_

### LINKED ISSUE #377: Show more names for tx in Tx History
When we reveal multiple bids, maybe there is another thing to display here instead of just one of the names (like either all if possible or none?)

Screen Shot 2021-06-21 at 10 51 17 AM

_Originally posted by @pinheadmz in https://github.com/kyokan/bob-wallet/issues/375#issuecomment-865096846_

### LINKED ISSUE #398: Could not resolve preferred inputs
## Expected Behavior

When I click "Reveal # bids within # days for the bids to count," I should be taken to the bids page to start the process of revealing said bids.

## Current Behavior

Issue title is the result.

## Context (Environment)

I'm using Ledger, that may be the issue.

## Logs

My log file is 26MB large...I think that exceeds GitHub's limit. Is there a way to reset the log?

## Screencap

SS 2021-07-30 at 4 40 06 PM

### LINKED ISSUE #420: Recovery phrase can be pasted
Howdy 👋

The recovery phrase during wallet creation can be pasted, but the text on screen says it can't be.

## Expected Behavior

Bob tells me pasting the recovery phrase is disabled to ensure I backed it up on paper.
I'm not quite sure that I expect that behaviour, but it's described in the UI, and I'd expect the text to be correct :)

## Current Behavior

I pasted my recovery phrase 👿.

## Steps to Reproduce

1. Create new wallet, name it.
2. Copy recovery phrase.
3. Paste recovery phrase.

## Context (Environment)

Creating a new wallet on Windows.

## Logs

[bob-debug-main.log](https://github.com/kyokan/bob-wallet/files/7402587/bob-debug-main.log)

## Screencap

image

### LINKED ISSUE #450: Need way to export transactions to CSV
## Expected Behavior
Need functionality to download all transactions to CSV. Currently got help from mod in Discord and only able to pull a JSON file which my accountant cannot parse.

## Current Behavior
(http://x:api-key@127.0.0.1:12039/wallet/$id/tx/history

Replace api key with key from settings -> wallet -> api key and $id with your wallet name
Then open in your browser, it should list all transactions)

### LINKED ISSUE #472: Passphrase not validated for each signing request.
When you sign a your first message, it properly validates your password, however on subsequent signings it presents the modal yet you can simply type anything as your passphrase and it will be accepted.

## Expected Behavior
Shouldn't sign if a wrong passphrase is entered

## Current Behavior
Signs regardless of what passphrase is entered

## Steps to Reproduce
1. Enter a message
2. Click sign
3. Enter your passphrase
4. Enter another message
5. Type in random text in the passphrase field

## Screencap
https://user-images.githubusercontent.com/12444228/154316349-d783295b-9171-4186-b01a-2a3dc3dd8896.mp4

### LINKED ISSUE #474: Wrong modal title when not revealing a bid
## Expected Behavior
When revealing a bid, when asked for the password, when the password modal window is closed, the alert message should say the bid was not revealed. 

## Current Behavior
The error message says the reveal request was submitted, but it is not.

## Steps to Reproduce

1. Click "Reveal" to reveal a bid.
1. When asked for the password, close the modal window.
1. The alert box has the incorrect title.

## Screencap

image

### LINKED ISSUE #475: [request] add niami to block explorer choices in settings
Bonus points, using the HNS+DANE domain https://niami ;-)

### LINKED ISSUE #492: Domain text in domain manager might be better to wrap
image
This image shows how you need to scroll sideways in the domain manager to see a long domain
This would look nicer if it was wrapped like below
image

## Steps to Reproduce
1. Have a really long domain
2. View the domain in bob domain manager

Low importance

### LINKED ISSUE #494: Select name to sign message
Signing in Bob wallet is a pain if the wallet has a ton of names since the name list is not ordered.

Ordering the list or a way to pre-select the list would be great.

### PR DESCRIPTION
**Pull request by rithvikvibhu**
Another batch of small changes. 1 commit = 1 issue.

### auction: show fail text on reveal cancel
(closes #474)
Cancelling when typing password will no longer give success notification.

### sign: lock wallet after signing msg
(closes #472)
Lock wallet afer signing.

### onboarding: warning on copy/paste seed
(closes #420)
Warns on copy/paste:
[Screen recording](https://user-images.githubusercontent.com/5113343/155724555-30e95027-3578-4434-968b-86bc86a76f82.mp4)

### account: error when double-spending w/ card
(closes #398)
No more errors that say "could not resolve preferred inputs".

### account: show all domains in tx list
(closes #377)
Expandable list of all involved names in transaction list.
image
image

### explorer: update list
(closes #475)
Update explorers list to:
- Add BlockExplorer, Niami, Niami (on Handshake)
- Remove hnsxplorer (offline 1+ year)
- Move HNScan and Shakescan to end (currently not working / offline)

### account: export transactions csv
(closes #450)
Adds a button under Transaction History to export all transactions in csv format.
image

### ci: remove node 14
Node.js v14 has been causing problems on this PR and others:
- v14 comes with a (non-updatable in gh actions) npm v6, which has node-gyp v5 built-in; this doesn't support VS 2022 which is available in GitHub Action's Windows environment, causing builds to fail
- It was hacky to delete `package-lock.json` (old npm doesn't like new v2 format) for node v14 jobs
- Electron recommends using the latest LTS, which is v16

Note: this is unrelated to the `common.gpyi not found` issue that makes Windows builds fail ~50% of the time (GitHub actions issue, workaround is to just re-run the job) - [ref1](https://github.com/AceCentre/EyeCommander/issues/51) [ref2](https://forums.meteor.com/t/gyp-error-while-installing-bcrypt-on-windows/54643) [ref3](https://github.com/serialport/node-serialport/issues/2322) [ref4](https://github.community/t/github-actions-error-on-npm-i/171968)

### topbar: remove total balance
(closes #174)
Total Balance includes value of names and is often confused with spendable balance. Since it isn't a useful value, it's removed from the topbar gear menu.

### records: tree status relative to update
(closes #293)
Tree update added in #289 always displayed the next tree update. Now it is aware of UPDATEs and shows:
image
image
In case of non-update being the latest tx, then it falls back old behavior (next update from current height).

### my-domain: wrap long name in title
(closes #492)
Long name overflowed off-screen, now it wraps to next lines.

### sign-msg: sort name dropdown
(closes #494)
The name dropdown in the Sign Message tab is now sorted so can find names easily.

### CODE REVIEW

**Comment by pinheadmz** [comment]
ACK on d25c34a3ab0e545161188435504292d944db9093 copy/paste seed, nice warnings ;-)

File: app/components/Transactions/index.js [hunk 1]
```diff
@@ -287,4 +327,33 @@ function debounce(func, timeout = 300){
...
+
+    // Negative
+    case 'SEND':
+    case 'BID':
+      return true;
+
+    // Should not reach here
+    default:
+      return false;
+  }
```
Comment (Falci) [inline app/components/Transactions/index.js:358]:
```js
return ['SEND', 'BID'].includes(type);
```

File: locales/en.json [hunk 2]
```diff
@@ -69,9 +68,11 @@
   "claimed": "Claimed",
   "closed": "Closed",
   "closedAuctionTitle": "Domain is no longer available",
+  "collapse": "Collapse",
```
Comment (Falci) [inline locales/en.json:71]: We should keep track of any new key added here, so we can add them to the other languages.

File: .github/workflows/build-and-test.yml [hunk 3]
```diff
@@ -16,15 +16,13 @@ jobs:
       fail-fast: false
       matrix:
         os: [windows-latest, ubuntu-latest]
-        node-version: ['14', '16']
+        node-version: ['16']
```
[the remark this answers is not in the document]
Comment (rithvikvibhu) [reply .github/workflows/build-and-test.yml:19]: Will have packages update PR later (electron, etc.) and can add it there. Btw curious if it builds fine on 18. Tried it?

File: app/components/Transactions/index.js (hunk 1 above)
Comment (rithvikvibhu) [reply app/components/Transactions/index.js:358]: True, this is much simpler! And can keep pos/neg/neutral as comments in short.
This is actually the same function that's used in `Transaction` (singular) component, that can be update too.

File: locales/en.json (hunk 2 above)
Comment (rithvikvibhu) [reply locales/en.json:71]: Yeah it's hard to keep track of translations across PRs and languages. So thinking of this before every release:
- Filter all PRs with `needs translation` label like this one
- Translators then work on the master branch directly instead of each branch
- Make sure all languages are done before each release

Also, there are scripts in the `scripts` directory that compare langs and find missing fields (relative to en.json).

File: .github/workflows/build-and-test.yml (hunk 3 above)
[the remark this answers is not in the document]
Comment (Falci) [reply .github/workflows/build-and-test.yml:19]: No, I didn't try.
